// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/token/token.proto

package token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generate Token Pair
type GenerateTokenPairRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AppId           string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Provider        string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	EmailVerified   bool                   `protobuf:"varint,5,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	SessionId       string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccessTokenTtl  int64                  `protobuf:"varint,7,opt,name=access_token_ttl,json=accessTokenTtl,proto3" json:"access_token_ttl,omitempty"`
	RefreshTokenTtl int64                  `protobuf:"varint,8,opt,name=refresh_token_ttl,json=refreshTokenTtl,proto3" json:"refresh_token_ttl,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateTokenPairRequest) Reset() {
	*x = GenerateTokenPairRequest{}
	mi := &file_proto_token_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenPairRequest) ProtoMessage() {}

func (x *GenerateTokenPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenPairRequest.ProtoReflect.Descriptor instead.
func (*GenerateTokenPairRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_token_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateTokenPairRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GenerateTokenPairRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateTokenPairRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GenerateTokenPairRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GenerateTokenPairRequest) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *GenerateTokenPairRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GenerateTokenPairRequest) GetAccessTokenTtl() int64 {
	if x != nil {
		return x.AccessTokenTtl
	}
	return 0
}

func (x *GenerateTokenPairRequest) GetRefreshTokenTtl() int64 {
	if x != nil {
		return x.RefreshTokenTtl
	}
	return 0
}

type GenerateTokenPairResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccessToken           string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpiresAt  int64                  `protobuf:"varint,3,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt int64                  `protobuf:"varint,4,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GenerateTokenPairResponse) Reset() {
	*x = GenerateTokenPairResponse{}
	mi := &file_proto_token_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenPairResponse) ProtoMessage() {}

func (x *GenerateTokenPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenPairResponse.ProtoReflect.Descriptor instead.
func (*GenerateTokenPairResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_token_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateTokenPairResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GenerateTokenPairResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *GenerateTokenPairResponse) GetAccessTokenExpiresAt() int64 {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return 0
}

func (x *GenerateTokenPairResponse) GetRefreshTokenExpiresAt() int64 {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return 0
}

// Refresh Tokens
type RefreshTokensRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken       string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AppId              string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	RotateRefreshToken bool                   `protobuf:"varint,3,opt,name=rotate_refresh_token,json=rotateRefreshToken,proto3" json:"rotate_refresh_token,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RefreshTokensRequest) Reset() {
	*x = RefreshTokensRequest{}
	mi := &file_proto_token_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokensRequest) ProtoMessage() {}

func (x *RefreshTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokensRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokensRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_token_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokensRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokensRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RefreshTokensRequest) GetRotateRefreshToken() bool {
	if x != nil {
		return x.RotateRefreshToken
	}
	return false
}

type RefreshTokensResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccessToken           string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken          *string                `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3,oneof" json:"refresh_token,omitempty"`
	AccessTokenExpiresAt  int64                  `protobuf:"varint,4,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt *int64                 `protobuf:"varint,5,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3,oneof" json:"refresh_token_expires_at,omitempty"`
	ErrorCode             string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RefreshTokensResponse) Reset() {
	*x = RefreshTokensResponse{}
	mi := &file_proto_token_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokensResponse) ProtoMessage() {}

func (x *RefreshTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokensResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokensResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_token_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokensResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshTokensResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokensResponse) GetRefreshToken() string {
	if x != nil && x.RefreshToken != nil {
		return *x.RefreshToken
	}
	return ""
}

func (x *RefreshTokensResponse) GetAccessTokenExpiresAt() int64 {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return 0
}

func (x *RefreshTokensResponse) GetRefreshTokenExpiresAt() int64 {
	if x != nil && x.RefreshTokenExpiresAt != nil {
		return *x.RefreshTokenExpiresAt
	}
	return 0
}

func (x *RefreshTokensResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RefreshTokensResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Revoke Token
type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"` // "access" or "refresh"
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_proto_token_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_token_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RevokeTokenRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *RevokeTokenRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_proto_token_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_token_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Public Keys for SDK verification
type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kid           string                 `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"` // Key ID
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	IsActive      bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_proto_token_token_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_token_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_proto_token_token_proto_rawDescGZIP(), []int{6}
}

func (x *PublicKey) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *PublicKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PublicKey) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetPublicKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeysRequest) Reset() {
	*x = GetPublicKeysRequest{}
	mi := &file_proto_token_token_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeysRequest) ProtoMessage() {}

func (x *GetPublicKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_token_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeysRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_token_token_proto_rawDescGZIP(), []int{7}
}

func (x *GetPublicKeysRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetPublicKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*PublicKey           `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeysResponse) Reset() {
	*x = GetPublicKeysResponse{}
	mi := &file_proto_token_token_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeysResponse) ProtoMessage() {}

func (x *GetPublicKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_token_token_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeysResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_token_token_proto_rawDescGZIP(), []int{8}
}

func (x *GetPublicKeysResponse) GetKeys() []*PublicKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_proto_token_token_proto protoreflect.FileDescriptor

const file_proto_token_token_proto_rawDesc = "" +
	"\n" +
	"\x17proto/token/token.proto\x12\x05token\"\x98\x02\n" +
	"\x18GenerateTokenPairRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12%\n" +
	"\x0eemail_verified\x18\x05 \x01(\bR\remailVerified\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12(\n" +
	"\x10access_token_ttl\x18\a \x01(\x03R\x0eaccessTokenTtl\x12*\n" +
	"\x11refresh_token_ttl\x18\b \x01(\x03R\x0frefreshTokenTtl\"\xd3\x01\n" +
	"\x19GenerateTokenPairResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x125\n" +
	"\x17access_token_expires_at\x18\x03 \x01(\x03R\x14accessTokenExpiresAt\x127\n" +
	"\x18refresh_token_expires_at\x18\x04 \x01(\x03R\x15refreshTokenExpiresAt\"\x84\x01\n" +
	"\x14RefreshTokensRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x120\n" +
	"\x14rotate_refresh_token\x18\x03 \x01(\bR\x12rotateRefreshToken\"\xe6\x02\n" +
	"\x15RefreshTokensResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12(\n" +
	"\rrefresh_token\x18\x03 \x01(\tH\x00R\frefreshToken\x88\x01\x01\x125\n" +
	"\x17access_token_expires_at\x18\x04 \x01(\x03R\x14accessTokenExpiresAt\x12<\n" +
	"\x18refresh_token_expires_at\x18\x05 \x01(\x03H\x01R\x15refreshTokenExpiresAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessageB\x10\n" +
	"\x0e_refresh_tokenB\x1b\n" +
	"\x19_refresh_token_expires_at\"`\n" +
	"\x12RevokeTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId\"/\n" +
	"\x13RevokeTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Y\n" +
	"\tPublicKey\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\tR\x03kid\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\"-\n" +
	"\x14GetPublicKeysRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"=\n" +
	"\x15GetPublicKeysResponse\x12$\n" +
	"\x04keys\x18\x01 \x03(\v2\x10.token.PublicKeyR\x04keys2\xc4\x02\n" +
	"\fTokenService\x12V\n" +
	"\x11GenerateTokenPair\x12\x1f.token.GenerateTokenPairRequest\x1a .token.GenerateTokenPairResponse\x12J\n" +
	"\rRefreshTokens\x12\x1b.token.RefreshTokensRequest\x1a\x1c.token.RefreshTokensResponse\x12D\n" +
	"\vRevokeToken\x12\x19.token.RevokeTokenRequest\x1a\x1a.token.RevokeTokenResponse\x12J\n" +
	"\rGetPublicKeys\x12\x1b.token.GetPublicKeysRequest\x1a\x1c.token.GetPublicKeysResponseB1Z/github.com/ayushdevan01/AuthService/proto/tokenb\x06proto3"

var (
	file_proto_token_token_proto_rawDescOnce sync.Once
	file_proto_token_token_proto_rawDescData []byte
)

func file_proto_token_token_proto_rawDescGZIP() []byte {
	file_proto_token_token_proto_rawDescOnce.Do(func() {
		file_proto_token_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_token_token_proto_rawDesc), len(file_proto_token_token_proto_rawDesc)))
	})
	return file_proto_token_token_proto_rawDescData
}

var file_proto_token_token_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_token_token_proto_goTypes = []any{
	(*GenerateTokenPairRequest)(nil),  // 0: token.GenerateTokenPairRequest
	(*GenerateTokenPairResponse)(nil), // 1: token.GenerateTokenPairResponse
	(*RefreshTokensRequest)(nil),      // 2: token.RefreshTokensRequest
	(*RefreshTokensResponse)(nil),     // 3: token.RefreshTokensResponse
	(*RevokeTokenRequest)(nil),        // 4: token.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),       // 5: token.RevokeTokenResponse
	(*PublicKey)(nil),                 // 6: token.PublicKey
	(*GetPublicKeysRequest)(nil),      // 7: token.GetPublicKeysRequest
	(*GetPublicKeysResponse)(nil),     // 8: token.GetPublicKeysResponse
}
var file_proto_token_token_proto_depIdxs = []int32{
	6, // 0: token.GetPublicKeysResponse.keys:type_name -> token.PublicKey
	0, // 1: token.TokenService.GenerateTokenPair:input_type -> token.GenerateTokenPairRequest
	2, // 2: token.TokenService.RefreshTokens:input_type -> token.RefreshTokensRequest
	4, // 3: token.TokenService.RevokeToken:input_type -> token.RevokeTokenRequest
	7, // 4: token.TokenService.GetPublicKeys:input_type -> token.GetPublicKeysRequest
	1, // 5: token.TokenService.GenerateTokenPair:output_type -> token.GenerateTokenPairResponse
	3, // 6: token.TokenService.RefreshTokens:output_type -> token.RefreshTokensResponse
	5, // 7: token.TokenService.RevokeToken:output_type -> token.RevokeTokenResponse
	8, // 8: token.TokenService.GetPublicKeys:output_type -> token.GetPublicKeysResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_token_token_proto_init() }
func file_proto_token_token_proto_init() {
	if File_proto_token_token_proto != nil {
		return
	}
	file_proto_token_token_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_token_token_proto_rawDesc), len(file_proto_token_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_token_token_proto_goTypes,
		DependencyIndexes: file_proto_token_token_proto_depIdxs,
		MessageInfos:      file_proto_token_token_proto_msgTypes,
	}.Build()
	File_proto_token_token_proto = out.File
	file_proto_token_token_proto_goTypes = nil
	file_proto_token_token_proto_depIdxs = nil
}
