// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/developer/developer.proto

package developer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeveloperService_Register_FullMethodName            = "/developer.DeveloperService/Register"
	DeveloperService_Login_FullMethodName               = "/developer.DeveloperService/Login"
	DeveloperService_Logout_FullMethodName              = "/developer.DeveloperService/Logout"
	DeveloperService_GetProfile_FullMethodName          = "/developer.DeveloperService/GetProfile"
	DeveloperService_UpdateProfile_FullMethodName       = "/developer.DeveloperService/UpdateProfile"
	DeveloperService_CreateApp_FullMethodName           = "/developer.DeveloperService/CreateApp"
	DeveloperService_GetApp_FullMethodName              = "/developer.DeveloperService/GetApp"
	DeveloperService_GetPublicApp_FullMethodName        = "/developer.DeveloperService/GetPublicApp"
	DeveloperService_ListApps_FullMethodName            = "/developer.DeveloperService/ListApps"
	DeveloperService_UpdateApp_FullMethodName           = "/developer.DeveloperService/UpdateApp"
	DeveloperService_DeleteApp_FullMethodName           = "/developer.DeveloperService/DeleteApp"
	DeveloperService_RotateApiKey_FullMethodName        = "/developer.DeveloperService/RotateApiKey"
	DeveloperService_VerifyApiKey_FullMethodName        = "/developer.DeveloperService/VerifyApiKey"
	DeveloperService_RotateSigningKeys_FullMethodName   = "/developer.DeveloperService/RotateSigningKeys"
	DeveloperService_ListSigningKeys_FullMethodName     = "/developer.DeveloperService/ListSigningKeys"
	DeveloperService_GetActiveSigningKey_FullMethodName = "/developer.DeveloperService/GetActiveSigningKey"
	DeveloperService_AddOAuthProvider_FullMethodName    = "/developer.DeveloperService/AddOAuthProvider"
	DeveloperService_GetOAuthProvider_FullMethodName    = "/developer.DeveloperService/GetOAuthProvider"
	DeveloperService_ListOAuthProviders_FullMethodName  = "/developer.DeveloperService/ListOAuthProviders"
	DeveloperService_UpdateOAuthProvider_FullMethodName = "/developer.DeveloperService/UpdateOAuthProvider"
	DeveloperService_DeleteOAuthProvider_FullMethodName = "/developer.DeveloperService/DeleteOAuthProvider"
)

// DeveloperServiceClient is the client API for DeveloperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeveloperServiceClient interface {
	// Developer Authentication
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	// App Management
	CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error)
	GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*GetAppResponse, error)
	GetPublicApp(ctx context.Context, in *GetPublicAppRequest, opts ...grpc.CallOption) (*GetPublicAppResponse, error)
	ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error)
	UpdateApp(ctx context.Context, in *UpdateAppRequest, opts ...grpc.CallOption) (*UpdateAppResponse, error)
	DeleteApp(ctx context.Context, in *DeleteAppRequest, opts ...grpc.CallOption) (*DeleteAppResponse, error)
	// Key Management
	RotateApiKey(ctx context.Context, in *RotateApiKeyRequest, opts ...grpc.CallOption) (*RotateApiKeyResponse, error)
	VerifyApiKey(ctx context.Context, in *VerifyApiKeyRequest, opts ...grpc.CallOption) (*VerifyApiKeyResponse, error)
	RotateSigningKeys(ctx context.Context, in *RotateSigningKeysRequest, opts ...grpc.CallOption) (*RotateSigningKeysResponse, error)
	ListSigningKeys(ctx context.Context, in *ListSigningKeysRequest, opts ...grpc.CallOption) (*ListSigningKeysResponse, error)
	GetActiveSigningKey(ctx context.Context, in *GetActiveSigningKeyRequest, opts ...grpc.CallOption) (*GetActiveSigningKeyResponse, error)
	// OAuth Provider Configuration
	AddOAuthProvider(ctx context.Context, in *AddOAuthProviderRequest, opts ...grpc.CallOption) (*AddOAuthProviderResponse, error)
	GetOAuthProvider(ctx context.Context, in *GetOAuthProviderRequest, opts ...grpc.CallOption) (*GetOAuthProviderResponse, error)
	ListOAuthProviders(ctx context.Context, in *ListOAuthProvidersRequest, opts ...grpc.CallOption) (*ListOAuthProvidersResponse, error)
	UpdateOAuthProvider(ctx context.Context, in *UpdateOAuthProviderRequest, opts ...grpc.CallOption) (*UpdateOAuthProviderResponse, error)
	DeleteOAuthProvider(ctx context.Context, in *DeleteOAuthProviderRequest, opts ...grpc.CallOption) (*DeleteOAuthProviderResponse, error)
}

type developerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeveloperServiceClient(cc grpc.ClientConnInterface) DeveloperServiceClient {
	return &developerServiceClient{cc}
}

func (c *developerServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, DeveloperService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, DeveloperService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, DeveloperService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, DeveloperService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, DeveloperService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAppResponse)
	err := c.cc.Invoke(ctx, DeveloperService_CreateApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*GetAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppResponse)
	err := c.cc.Invoke(ctx, DeveloperService_GetApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) GetPublicApp(ctx context.Context, in *GetPublicAppRequest, opts ...grpc.CallOption) (*GetPublicAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicAppResponse)
	err := c.cc.Invoke(ctx, DeveloperService_GetPublicApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppsResponse)
	err := c.cc.Invoke(ctx, DeveloperService_ListApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) UpdateApp(ctx context.Context, in *UpdateAppRequest, opts ...grpc.CallOption) (*UpdateAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAppResponse)
	err := c.cc.Invoke(ctx, DeveloperService_UpdateApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) DeleteApp(ctx context.Context, in *DeleteAppRequest, opts ...grpc.CallOption) (*DeleteAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAppResponse)
	err := c.cc.Invoke(ctx, DeveloperService_DeleteApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) RotateApiKey(ctx context.Context, in *RotateApiKeyRequest, opts ...grpc.CallOption) (*RotateApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateApiKeyResponse)
	err := c.cc.Invoke(ctx, DeveloperService_RotateApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) VerifyApiKey(ctx context.Context, in *VerifyApiKeyRequest, opts ...grpc.CallOption) (*VerifyApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyApiKeyResponse)
	err := c.cc.Invoke(ctx, DeveloperService_VerifyApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) RotateSigningKeys(ctx context.Context, in *RotateSigningKeysRequest, opts ...grpc.CallOption) (*RotateSigningKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateSigningKeysResponse)
	err := c.cc.Invoke(ctx, DeveloperService_RotateSigningKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) ListSigningKeys(ctx context.Context, in *ListSigningKeysRequest, opts ...grpc.CallOption) (*ListSigningKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSigningKeysResponse)
	err := c.cc.Invoke(ctx, DeveloperService_ListSigningKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) GetActiveSigningKey(ctx context.Context, in *GetActiveSigningKeyRequest, opts ...grpc.CallOption) (*GetActiveSigningKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveSigningKeyResponse)
	err := c.cc.Invoke(ctx, DeveloperService_GetActiveSigningKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) AddOAuthProvider(ctx context.Context, in *AddOAuthProviderRequest, opts ...grpc.CallOption) (*AddOAuthProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddOAuthProviderResponse)
	err := c.cc.Invoke(ctx, DeveloperService_AddOAuthProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) GetOAuthProvider(ctx context.Context, in *GetOAuthProviderRequest, opts ...grpc.CallOption) (*GetOAuthProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOAuthProviderResponse)
	err := c.cc.Invoke(ctx, DeveloperService_GetOAuthProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) ListOAuthProviders(ctx context.Context, in *ListOAuthProvidersRequest, opts ...grpc.CallOption) (*ListOAuthProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOAuthProvidersResponse)
	err := c.cc.Invoke(ctx, DeveloperService_ListOAuthProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) UpdateOAuthProvider(ctx context.Context, in *UpdateOAuthProviderRequest, opts ...grpc.CallOption) (*UpdateOAuthProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOAuthProviderResponse)
	err := c.cc.Invoke(ctx, DeveloperService_UpdateOAuthProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developerServiceClient) DeleteOAuthProvider(ctx context.Context, in *DeleteOAuthProviderRequest, opts ...grpc.CallOption) (*DeleteOAuthProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOAuthProviderResponse)
	err := c.cc.Invoke(ctx, DeveloperService_DeleteOAuthProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeveloperServiceServer is the server API for DeveloperService service.
// All implementations must embed UnimplementedDeveloperServiceServer
// for forward compatibility.
type DeveloperServiceServer interface {
	// Developer Authentication
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	// App Management
	CreateApp(context.Context, *CreateAppRequest) (*CreateAppResponse, error)
	GetApp(context.Context, *GetAppRequest) (*GetAppResponse, error)
	GetPublicApp(context.Context, *GetPublicAppRequest) (*GetPublicAppResponse, error)
	ListApps(context.Context, *ListAppsRequest) (*ListAppsResponse, error)
	UpdateApp(context.Context, *UpdateAppRequest) (*UpdateAppResponse, error)
	DeleteApp(context.Context, *DeleteAppRequest) (*DeleteAppResponse, error)
	// Key Management
	RotateApiKey(context.Context, *RotateApiKeyRequest) (*RotateApiKeyResponse, error)
	VerifyApiKey(context.Context, *VerifyApiKeyRequest) (*VerifyApiKeyResponse, error)
	RotateSigningKeys(context.Context, *RotateSigningKeysRequest) (*RotateSigningKeysResponse, error)
	ListSigningKeys(context.Context, *ListSigningKeysRequest) (*ListSigningKeysResponse, error)
	GetActiveSigningKey(context.Context, *GetActiveSigningKeyRequest) (*GetActiveSigningKeyResponse, error)
	// OAuth Provider Configuration
	AddOAuthProvider(context.Context, *AddOAuthProviderRequest) (*AddOAuthProviderResponse, error)
	GetOAuthProvider(context.Context, *GetOAuthProviderRequest) (*GetOAuthProviderResponse, error)
	ListOAuthProviders(context.Context, *ListOAuthProvidersRequest) (*ListOAuthProvidersResponse, error)
	UpdateOAuthProvider(context.Context, *UpdateOAuthProviderRequest) (*UpdateOAuthProviderResponse, error)
	DeleteOAuthProvider(context.Context, *DeleteOAuthProviderRequest) (*DeleteOAuthProviderResponse, error)
	mustEmbedUnimplementedDeveloperServiceServer()
}

// UnimplementedDeveloperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeveloperServiceServer struct{}

func (UnimplementedDeveloperServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedDeveloperServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedDeveloperServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedDeveloperServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedDeveloperServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedDeveloperServiceServer) CreateApp(context.Context, *CreateAppRequest) (*CreateAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateApp not implemented")
}
func (UnimplementedDeveloperServiceServer) GetApp(context.Context, *GetAppRequest) (*GetAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApp not implemented")
}
func (UnimplementedDeveloperServiceServer) GetPublicApp(context.Context, *GetPublicAppRequest) (*GetPublicAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicApp not implemented")
}
func (UnimplementedDeveloperServiceServer) ListApps(context.Context, *ListAppsRequest) (*ListAppsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApps not implemented")
}
func (UnimplementedDeveloperServiceServer) UpdateApp(context.Context, *UpdateAppRequest) (*UpdateAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateApp not implemented")
}
func (UnimplementedDeveloperServiceServer) DeleteApp(context.Context, *DeleteAppRequest) (*DeleteAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteApp not implemented")
}
func (UnimplementedDeveloperServiceServer) RotateApiKey(context.Context, *RotateApiKeyRequest) (*RotateApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateApiKey not implemented")
}
func (UnimplementedDeveloperServiceServer) VerifyApiKey(context.Context, *VerifyApiKeyRequest) (*VerifyApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyApiKey not implemented")
}
func (UnimplementedDeveloperServiceServer) RotateSigningKeys(context.Context, *RotateSigningKeysRequest) (*RotateSigningKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateSigningKeys not implemented")
}
func (UnimplementedDeveloperServiceServer) ListSigningKeys(context.Context, *ListSigningKeysRequest) (*ListSigningKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSigningKeys not implemented")
}
func (UnimplementedDeveloperServiceServer) GetActiveSigningKey(context.Context, *GetActiveSigningKeyRequest) (*GetActiveSigningKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveSigningKey not implemented")
}
func (UnimplementedDeveloperServiceServer) AddOAuthProvider(context.Context, *AddOAuthProviderRequest) (*AddOAuthProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddOAuthProvider not implemented")
}
func (UnimplementedDeveloperServiceServer) GetOAuthProvider(context.Context, *GetOAuthProviderRequest) (*GetOAuthProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOAuthProvider not implemented")
}
func (UnimplementedDeveloperServiceServer) ListOAuthProviders(context.Context, *ListOAuthProvidersRequest) (*ListOAuthProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOAuthProviders not implemented")
}
func (UnimplementedDeveloperServiceServer) UpdateOAuthProvider(context.Context, *UpdateOAuthProviderRequest) (*UpdateOAuthProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOAuthProvider not implemented")
}
func (UnimplementedDeveloperServiceServer) DeleteOAuthProvider(context.Context, *DeleteOAuthProviderRequest) (*DeleteOAuthProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOAuthProvider not implemented")
}
func (UnimplementedDeveloperServiceServer) mustEmbedUnimplementedDeveloperServiceServer() {}
func (UnimplementedDeveloperServiceServer) testEmbeddedByValue()                          {}

// UnsafeDeveloperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeveloperServiceServer will
// result in compilation errors.
type UnsafeDeveloperServiceServer interface {
	mustEmbedUnimplementedDeveloperServiceServer()
}

func RegisterDeveloperServiceServer(s grpc.ServiceRegistrar, srv DeveloperServiceServer) {
	// If the following call panics, it indicates UnimplementedDeveloperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeveloperService_ServiceDesc, srv)
}

func _DeveloperService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_CreateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).CreateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_CreateApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).CreateApp(ctx, req.(*CreateAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_GetApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).GetApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_GetApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).GetApp(ctx, req.(*GetAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_GetPublicApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).GetPublicApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_GetPublicApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).GetPublicApp(ctx, req.(*GetPublicAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_ListApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).ListApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_ListApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).ListApps(ctx, req.(*ListAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_UpdateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).UpdateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_UpdateApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).UpdateApp(ctx, req.(*UpdateAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_DeleteApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).DeleteApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_DeleteApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).DeleteApp(ctx, req.(*DeleteAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_RotateApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).RotateApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_RotateApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).RotateApiKey(ctx, req.(*RotateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_VerifyApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).VerifyApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_VerifyApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).VerifyApiKey(ctx, req.(*VerifyApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_RotateSigningKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateSigningKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).RotateSigningKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_RotateSigningKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).RotateSigningKeys(ctx, req.(*RotateSigningKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_ListSigningKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSigningKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).ListSigningKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_ListSigningKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).ListSigningKeys(ctx, req.(*ListSigningKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_GetActiveSigningKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveSigningKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).GetActiveSigningKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_GetActiveSigningKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).GetActiveSigningKey(ctx, req.(*GetActiveSigningKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_AddOAuthProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOAuthProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).AddOAuthProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_AddOAuthProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).AddOAuthProvider(ctx, req.(*AddOAuthProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_GetOAuthProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOAuthProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).GetOAuthProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_GetOAuthProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).GetOAuthProvider(ctx, req.(*GetOAuthProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_ListOAuthProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOAuthProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).ListOAuthProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_ListOAuthProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).ListOAuthProviders(ctx, req.(*ListOAuthProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_UpdateOAuthProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOAuthProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).UpdateOAuthProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_UpdateOAuthProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).UpdateOAuthProvider(ctx, req.(*UpdateOAuthProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeveloperService_DeleteOAuthProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOAuthProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeveloperServiceServer).DeleteOAuthProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeveloperService_DeleteOAuthProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeveloperServiceServer).DeleteOAuthProvider(ctx, req.(*DeleteOAuthProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeveloperService_ServiceDesc is the grpc.ServiceDesc for DeveloperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeveloperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "developer.DeveloperService",
	HandlerType: (*DeveloperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _DeveloperService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _DeveloperService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _DeveloperService_Logout_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _DeveloperService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _DeveloperService_UpdateProfile_Handler,
		},
		{
			MethodName: "CreateApp",
			Handler:    _DeveloperService_CreateApp_Handler,
		},
		{
			MethodName: "GetApp",
			Handler:    _DeveloperService_GetApp_Handler,
		},
		{
			MethodName: "GetPublicApp",
			Handler:    _DeveloperService_GetPublicApp_Handler,
		},
		{
			MethodName: "ListApps",
			Handler:    _DeveloperService_ListApps_Handler,
		},
		{
			MethodName: "UpdateApp",
			Handler:    _DeveloperService_UpdateApp_Handler,
		},
		{
			MethodName: "DeleteApp",
			Handler:    _DeveloperService_DeleteApp_Handler,
		},
		{
			MethodName: "RotateApiKey",
			Handler:    _DeveloperService_RotateApiKey_Handler,
		},
		{
			MethodName: "VerifyApiKey",
			Handler:    _DeveloperService_VerifyApiKey_Handler,
		},
		{
			MethodName: "RotateSigningKeys",
			Handler:    _DeveloperService_RotateSigningKeys_Handler,
		},
		{
			MethodName: "ListSigningKeys",
			Handler:    _DeveloperService_ListSigningKeys_Handler,
		},
		{
			MethodName: "GetActiveSigningKey",
			Handler:    _DeveloperService_GetActiveSigningKey_Handler,
		},
		{
			MethodName: "AddOAuthProvider",
			Handler:    _DeveloperService_AddOAuthProvider_Handler,
		},
		{
			MethodName: "GetOAuthProvider",
			Handler:    _DeveloperService_GetOAuthProvider_Handler,
		},
		{
			MethodName: "ListOAuthProviders",
			Handler:    _DeveloperService_ListOAuthProviders_Handler,
		},
		{
			MethodName: "UpdateOAuthProvider",
			Handler:    _DeveloperService_UpdateOAuthProvider_Handler,
		},
		{
			MethodName: "DeleteOAuthProvider",
			Handler:    _DeveloperService_DeleteOAuthProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/developer/developer.proto",
}
