// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/developer/developer.proto

package developer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Developer entity
type Developer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Developer) Reset() {
	*x = Developer{}
	mi := &file_proto_developer_developer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Developer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Developer) ProtoMessage() {}

func (x *Developer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Developer.ProtoReflect.Descriptor instead.
func (*Developer) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{0}
}

func (x *Developer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Developer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Developer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Developer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Developer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Developer Authentication
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Developer     *Developer             `protobuf:"bytes,1,opt,name=developer,proto3" json:"developer,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetDeveloper() *Developer {
	if x != nil {
		return x.Developer
	}
	return nil
}

func (x *RegisterResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Developer     *Developer             `protobuf:"bytes,1,opt,name=developer,proto3" json:"developer,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetDeveloper() *Developer {
	if x != nil {
		return x.Developer
	}
	return nil
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeveloperId   string                 `protobuf:"bytes,1,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeveloperId   string                 `protobuf:"bytes,1,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfileRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Developer     *Developer             `protobuf:"bytes,1,opt,name=developer,proto3" json:"developer,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileResponse) GetDeveloper() *Developer {
	if x != nil {
		return x.Developer
	}
	return nil
}

func (x *GetProfileResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeveloperId   string                 `protobuf:"bytes,1,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Password      *string                `protobuf:"bytes,3,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProfileRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Developer     *Developer             `protobuf:"bytes,1,opt,name=developer,proto3" json:"developer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProfileResponse) GetDeveloper() *Developer {
	if x != nil {
		return x.Developer
	}
	return nil
}

// App entity
type App struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeveloperId              string                 `protobuf:"bytes,2,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	Name                     string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AppId                    string                 `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	LogoUrl                  string                 `protobuf:"bytes,5,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	RedirectUrls             []string               `protobuf:"bytes,6,rep,name=redirect_urls,json=redirectUrls,proto3" json:"redirect_urls,omitempty"`
	CreatedAt                *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RequireEmailVerification bool                   `protobuf:"varint,9,opt,name=require_email_verification,json=requireEmailVerification,proto3" json:"require_email_verification,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_proto_developer_developer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{11}
}

func (x *App) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *App) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *App) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *App) GetRedirectUrls() []string {
	if x != nil {
		return x.RedirectUrls
	}
	return nil
}

func (x *App) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *App) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *App) GetRequireEmailVerification() bool {
	if x != nil {
		return x.RequireEmailVerification
	}
	return false
}

// App Management
type CreateAppRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	DeveloperId              string                 `protobuf:"bytes,1,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	Name                     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LogoUrl                  string                 `protobuf:"bytes,3,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	RedirectUrls             []string               `protobuf:"bytes,4,rep,name=redirect_urls,json=redirectUrls,proto3" json:"redirect_urls,omitempty"`
	RequireEmailVerification bool                   `protobuf:"varint,5,opt,name=require_email_verification,json=requireEmailVerification,proto3" json:"require_email_verification,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateAppRequest) Reset() {
	*x = CreateAppRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppRequest) ProtoMessage() {}

func (x *CreateAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppRequest.ProtoReflect.Descriptor instead.
func (*CreateAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{12}
}

func (x *CreateAppRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *CreateAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAppRequest) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *CreateAppRequest) GetRedirectUrls() []string {
	if x != nil {
		return x.RedirectUrls
	}
	return nil
}

func (x *CreateAppRequest) GetRequireEmailVerification() bool {
	if x != nil {
		return x.RequireEmailVerification
	}
	return false
}

type CreateAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *App                   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	SigningKey    *SigningKey            `protobuf:"bytes,3,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppResponse) Reset() {
	*x = CreateAppResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppResponse) ProtoMessage() {}

func (x *CreateAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppResponse.ProtoReflect.Descriptor instead.
func (*CreateAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{13}
}

func (x *CreateAppResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *CreateAppResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateAppResponse) GetSigningKey() *SigningKey {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

type GetAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppRequest) Reset() {
	*x = GetAppRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppRequest) ProtoMessage() {}

func (x *GetAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppRequest.ProtoReflect.Descriptor instead.
func (*GetAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{14}
}

func (x *GetAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *App                   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppResponse) Reset() {
	*x = GetAppResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppResponse) ProtoMessage() {}

func (x *GetAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppResponse.ProtoReflect.Descriptor instead.
func (*GetAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{15}
}

func (x *GetAppResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *GetAppResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetPublicAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicAppRequest) Reset() {
	*x = GetPublicAppRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicAppRequest) ProtoMessage() {}

func (x *GetPublicAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicAppRequest.ProtoReflect.Descriptor instead.
func (*GetPublicAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{16}
}

func (x *GetPublicAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetPublicAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *App                   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicAppResponse) Reset() {
	*x = GetPublicAppResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicAppResponse) ProtoMessage() {}

func (x *GetPublicAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicAppResponse.ProtoReflect.Descriptor instead.
func (*GetPublicAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{17}
}

func (x *GetPublicAppResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *GetPublicAppResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ListAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeveloperId   string                 `protobuf:"bytes,1,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsRequest) Reset() {
	*x = ListAppsRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsRequest) ProtoMessage() {}

func (x *ListAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsRequest.ProtoReflect.Descriptor instead.
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{18}
}

func (x *ListAppsRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

type ListAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*App                 `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsResponse) Reset() {
	*x = ListAppsResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsResponse) ProtoMessage() {}

func (x *ListAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsResponse.ProtoReflect.Descriptor instead.
func (*ListAppsResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{19}
}

func (x *ListAppsResponse) GetApps() []*App {
	if x != nil {
		return x.Apps
	}
	return nil
}

type UpdateAppRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeveloperId              string                 `protobuf:"bytes,2,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	Name                     *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	LogoUrl                  *string                `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3,oneof" json:"logo_url,omitempty"`
	RedirectUrls             []string               `protobuf:"bytes,5,rep,name=redirect_urls,json=redirectUrls,proto3" json:"redirect_urls,omitempty"`
	RequireEmailVerification *bool                  `protobuf:"varint,6,opt,name=require_email_verification,json=requireEmailVerification,proto3,oneof" json:"require_email_verification,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpdateAppRequest) Reset() {
	*x = UpdateAppRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppRequest) ProtoMessage() {}

func (x *UpdateAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateAppRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAppRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *UpdateAppRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateAppRequest) GetLogoUrl() string {
	if x != nil && x.LogoUrl != nil {
		return *x.LogoUrl
	}
	return ""
}

func (x *UpdateAppRequest) GetRedirectUrls() []string {
	if x != nil {
		return x.RedirectUrls
	}
	return nil
}

func (x *UpdateAppRequest) GetRequireEmailVerification() bool {
	if x != nil && x.RequireEmailVerification != nil {
		return *x.RequireEmailVerification
	}
	return false
}

type UpdateAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *App                   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppResponse) Reset() {
	*x = UpdateAppResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppResponse) ProtoMessage() {}

func (x *UpdateAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppResponse.ProtoReflect.Descriptor instead.
func (*UpdateAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateAppResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type DeleteAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeveloperId   string                 `protobuf:"bytes,2,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppRequest) Reset() {
	*x = DeleteAppRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppRequest) ProtoMessage() {}

func (x *DeleteAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteAppRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteAppRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

type DeleteAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppResponse) Reset() {
	*x = DeleteAppResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppResponse) ProtoMessage() {}

func (x *DeleteAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteAppResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Signing Key entity
type SigningKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Kid           string                 `protobuf:"bytes,3,opt,name=kid,proto3" json:"kid,omitempty"` // "key-2026-02-08"
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RotatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=rotated_at,json=rotatedAt,proto3" json:"rotated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningKey) Reset() {
	*x = SigningKey{}
	mi := &file_proto_developer_developer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningKey) ProtoMessage() {}

func (x *SigningKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningKey.ProtoReflect.Descriptor instead.
func (*SigningKey) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{24}
}

func (x *SigningKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SigningKey) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SigningKey) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *SigningKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SigningKey) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *SigningKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SigningKey) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SigningKey) GetRotatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RotatedAt
	}
	return nil
}

// Key Management
type RotateApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DeveloperId   string                 `protobuf:"bytes,2,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateApiKeyRequest) Reset() {
	*x = RotateApiKeyRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateApiKeyRequest) ProtoMessage() {}

func (x *RotateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{25}
}

func (x *RotateApiKeyRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RotateApiKeyRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

type RotateApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewApiKey     string                 `protobuf:"bytes,1,opt,name=new_api_key,json=newApiKey,proto3" json:"new_api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateApiKeyResponse) Reset() {
	*x = RotateApiKeyResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateApiKeyResponse) ProtoMessage() {}

func (x *RotateApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateApiKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{26}
}

func (x *RotateApiKeyResponse) GetNewApiKey() string {
	if x != nil {
		return x.NewApiKey
	}
	return ""
}

type VerifyApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyApiKeyRequest) Reset() {
	*x = VerifyApiKeyRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyApiKeyRequest) ProtoMessage() {}

func (x *VerifyApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyApiKeyRequest.ProtoReflect.Descriptor instead.
func (*VerifyApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{27}
}

func (x *VerifyApiKeyRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *VerifyApiKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type VerifyApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyApiKeyResponse) Reset() {
	*x = VerifyApiKeyResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyApiKeyResponse) ProtoMessage() {}

func (x *VerifyApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyApiKeyResponse.ProtoReflect.Descriptor instead.
func (*VerifyApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{28}
}

func (x *VerifyApiKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type RotateSigningKeysRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AppId            string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DeveloperId      string                 `protobuf:"bytes,2,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	GracePeriodHours int32                  `protobuf:"varint,3,opt,name=grace_period_hours,json=gracePeriodHours,proto3" json:"grace_period_hours,omitempty"` // Default: 24
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RotateSigningKeysRequest) Reset() {
	*x = RotateSigningKeysRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSigningKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSigningKeysRequest) ProtoMessage() {}

func (x *RotateSigningKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSigningKeysRequest.ProtoReflect.Descriptor instead.
func (*RotateSigningKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{29}
}

func (x *RotateSigningKeysRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RotateSigningKeysRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *RotateSigningKeysRequest) GetGracePeriodHours() int32 {
	if x != nil {
		return x.GracePeriodHours
	}
	return 0
}

type RotateSigningKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewKey        *SigningKey            `protobuf:"bytes,1,opt,name=new_key,json=newKey,proto3" json:"new_key,omitempty"`
	OldKey        *SigningKey            `protobuf:"bytes,2,opt,name=old_key,json=oldKey,proto3" json:"old_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateSigningKeysResponse) Reset() {
	*x = RotateSigningKeysResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSigningKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSigningKeysResponse) ProtoMessage() {}

func (x *RotateSigningKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSigningKeysResponse.ProtoReflect.Descriptor instead.
func (*RotateSigningKeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{30}
}

func (x *RotateSigningKeysResponse) GetNewKey() *SigningKey {
	if x != nil {
		return x.NewKey
	}
	return nil
}

func (x *RotateSigningKeysResponse) GetOldKey() *SigningKey {
	if x != nil {
		return x.OldKey
	}
	return nil
}

type ListSigningKeysRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DeveloperId    string                 `protobuf:"bytes,2,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	IncludeExpired bool                   `protobuf:"varint,3,opt,name=include_expired,json=includeExpired,proto3" json:"include_expired,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListSigningKeysRequest) Reset() {
	*x = ListSigningKeysRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSigningKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSigningKeysRequest) ProtoMessage() {}

func (x *ListSigningKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSigningKeysRequest.ProtoReflect.Descriptor instead.
func (*ListSigningKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{31}
}

func (x *ListSigningKeysRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ListSigningKeysRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *ListSigningKeysRequest) GetIncludeExpired() bool {
	if x != nil {
		return x.IncludeExpired
	}
	return false
}

type ListSigningKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*SigningKey          `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSigningKeysResponse) Reset() {
	*x = ListSigningKeysResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSigningKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSigningKeysResponse) ProtoMessage() {}

func (x *ListSigningKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSigningKeysResponse.ProtoReflect.Descriptor instead.
func (*ListSigningKeysResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{32}
}

func (x *ListSigningKeysResponse) GetKeys() []*SigningKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetActiveSigningKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSigningKeyRequest) Reset() {
	*x = GetActiveSigningKeyRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSigningKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSigningKeyRequest) ProtoMessage() {}

func (x *GetActiveSigningKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSigningKeyRequest.ProtoReflect.Descriptor instead.
func (*GetActiveSigningKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{33}
}

func (x *GetActiveSigningKeyRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetActiveSigningKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *SigningKey            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"` // used by token service
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveSigningKeyResponse) Reset() {
	*x = GetActiveSigningKeyResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveSigningKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveSigningKeyResponse) ProtoMessage() {}

func (x *GetActiveSigningKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveSigningKeyResponse.ProtoReflect.Descriptor instead.
func (*GetActiveSigningKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{34}
}

func (x *GetActiveSigningKeyResponse) GetKey() *SigningKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetActiveSigningKeyResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *GetActiveSigningKeyResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// OAuth Provider
type OAuthProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"` // "google", "github" etc
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Scopes        []string               `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthProvider) Reset() {
	*x = OAuthProvider{}
	mi := &file_proto_developer_developer_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthProvider) ProtoMessage() {}

func (x *OAuthProvider) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthProvider.ProtoReflect.Descriptor instead.
func (*OAuthProvider) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{35}
}

func (x *OAuthProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OAuthProvider) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *OAuthProvider) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OAuthProvider) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuthProvider) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *OAuthProvider) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OAuthProvider) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// OAuth Provider Configuration
type AddOAuthProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DeveloperId   string                 `protobuf:"bytes,2,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,5,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Scopes        []string               `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOAuthProviderRequest) Reset() {
	*x = AddOAuthProviderRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOAuthProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOAuthProviderRequest) ProtoMessage() {}

func (x *AddOAuthProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOAuthProviderRequest.ProtoReflect.Descriptor instead.
func (*AddOAuthProviderRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{36}
}

func (x *AddOAuthProviderRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AddOAuthProviderRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *AddOAuthProviderRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AddOAuthProviderRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AddOAuthProviderRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *AddOAuthProviderRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type AddOAuthProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *OAuthProvider         `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOAuthProviderResponse) Reset() {
	*x = AddOAuthProviderResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOAuthProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOAuthProviderResponse) ProtoMessage() {}

func (x *AddOAuthProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOAuthProviderResponse.ProtoReflect.Descriptor instead.
func (*AddOAuthProviderResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{37}
}

func (x *AddOAuthProviderResponse) GetProvider() *OAuthProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type GetOAuthProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuthProviderRequest) Reset() {
	*x = GetOAuthProviderRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthProviderRequest) ProtoMessage() {}

func (x *GetOAuthProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthProviderRequest.ProtoReflect.Descriptor instead.
func (*GetOAuthProviderRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{38}
}

func (x *GetOAuthProviderRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetOAuthProviderRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type GetOAuthProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *OAuthProvider         `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"` // used by auth service
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuthProviderResponse) Reset() {
	*x = GetOAuthProviderResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuthProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuthProviderResponse) ProtoMessage() {}

func (x *GetOAuthProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuthProviderResponse.ProtoReflect.Descriptor instead.
func (*GetOAuthProviderResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{39}
}

func (x *GetOAuthProviderResponse) GetProvider() *OAuthProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *GetOAuthProviderResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *GetOAuthProviderResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ListOAuthProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DeveloperId   string                 `protobuf:"bytes,2,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOAuthProvidersRequest) Reset() {
	*x = ListOAuthProvidersRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOAuthProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOAuthProvidersRequest) ProtoMessage() {}

func (x *ListOAuthProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOAuthProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListOAuthProvidersRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{40}
}

func (x *ListOAuthProvidersRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ListOAuthProvidersRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

type ListOAuthProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*OAuthProvider       `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOAuthProvidersResponse) Reset() {
	*x = ListOAuthProvidersResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOAuthProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOAuthProvidersResponse) ProtoMessage() {}

func (x *ListOAuthProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOAuthProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListOAuthProvidersResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{41}
}

func (x *ListOAuthProvidersResponse) GetProviders() []*OAuthProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type UpdateOAuthProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DeveloperId   string                 `protobuf:"bytes,2,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ClientId      *string                `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	ClientSecret  *string                `protobuf:"bytes,5,opt,name=client_secret,json=clientSecret,proto3,oneof" json:"client_secret,omitempty"`
	Scopes        []string               `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Enabled       *bool                  `protobuf:"varint,7,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOAuthProviderRequest) Reset() {
	*x = UpdateOAuthProviderRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOAuthProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOAuthProviderRequest) ProtoMessage() {}

func (x *UpdateOAuthProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOAuthProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOAuthProviderRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{42}
}

func (x *UpdateOAuthProviderRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UpdateOAuthProviderRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *UpdateOAuthProviderRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UpdateOAuthProviderRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *UpdateOAuthProviderRequest) GetClientSecret() string {
	if x != nil && x.ClientSecret != nil {
		return *x.ClientSecret
	}
	return ""
}

func (x *UpdateOAuthProviderRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *UpdateOAuthProviderRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type UpdateOAuthProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *OAuthProvider         `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOAuthProviderResponse) Reset() {
	*x = UpdateOAuthProviderResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOAuthProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOAuthProviderResponse) ProtoMessage() {}

func (x *UpdateOAuthProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOAuthProviderResponse.ProtoReflect.Descriptor instead.
func (*UpdateOAuthProviderResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{43}
}

func (x *UpdateOAuthProviderResponse) GetProvider() *OAuthProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type DeleteOAuthProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DeveloperId   string                 `protobuf:"bytes,2,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOAuthProviderRequest) Reset() {
	*x = DeleteOAuthProviderRequest{}
	mi := &file_proto_developer_developer_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOAuthProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOAuthProviderRequest) ProtoMessage() {}

func (x *DeleteOAuthProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOAuthProviderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOAuthProviderRequest) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{44}
}

func (x *DeleteOAuthProviderRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *DeleteOAuthProviderRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *DeleteOAuthProviderRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type DeleteOAuthProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOAuthProviderResponse) Reset() {
	*x = DeleteOAuthProviderResponse{}
	mi := &file_proto_developer_developer_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOAuthProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOAuthProviderResponse) ProtoMessage() {}

func (x *DeleteOAuthProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_developer_developer_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOAuthProviderResponse.ProtoReflect.Descriptor instead.
func (*DeleteOAuthProviderResponse) Descriptor() ([]byte, []int) {
	return file_proto_developer_developer_proto_rawDescGZIP(), []int{45}
}

func (x *DeleteOAuthProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_developer_developer_proto protoreflect.FileDescriptor

const file_proto_developer_developer_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/developer/developer.proto\x12\tdeveloper\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\tDeveloper\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"W\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"i\n" +
	"\x10RegisterResponse\x122\n" +
	"\tdeveloper\x18\x01 \x01(\v2\x14.developer.DeveloperR\tdeveloper\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"f\n" +
	"\rLoginResponse\x122\n" +
	"\tdeveloper\x18\x01 \x01(\v2\x14.developer.DeveloperR\tdeveloper\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"2\n" +
	"\rLogoutRequest\x12!\n" +
	"\fdeveloper_id\x18\x01 \x01(\tR\vdeveloperId\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"6\n" +
	"\x11GetProfileRequest\x12!\n" +
	"\fdeveloper_id\x18\x01 \x01(\tR\vdeveloperId\"^\n" +
	"\x12GetProfileResponse\x122\n" +
	"\tdeveloper\x18\x01 \x01(\v2\x14.developer.DeveloperR\tdeveloper\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x89\x01\n" +
	"\x14UpdateProfileRequest\x12!\n" +
	"\fdeveloper_id\x18\x01 \x01(\tR\vdeveloperId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x03 \x01(\tH\x01R\bpassword\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_password\"K\n" +
	"\x15UpdateProfileResponse\x122\n" +
	"\tdeveloper\x18\x01 \x01(\v2\x14.developer.DeveloperR\tdeveloper\"\xd7\x02\n" +
	"\x03App\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdeveloper_id\x18\x02 \x01(\tR\vdeveloperId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\tR\x05appId\x12\x19\n" +
	"\blogo_url\x18\x05 \x01(\tR\alogoUrl\x12#\n" +
	"\rredirect_urls\x18\x06 \x03(\tR\fredirectUrls\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12<\n" +
	"\x1arequire_email_verification\x18\t \x01(\bR\x18requireEmailVerification\"\xc7\x01\n" +
	"\x10CreateAppRequest\x12!\n" +
	"\fdeveloper_id\x18\x01 \x01(\tR\vdeveloperId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\blogo_url\x18\x03 \x01(\tR\alogoUrl\x12#\n" +
	"\rredirect_urls\x18\x04 \x03(\tR\fredirectUrls\x12<\n" +
	"\x1arequire_email_verification\x18\x05 \x01(\bR\x18requireEmailVerification\"\x86\x01\n" +
	"\x11CreateAppResponse\x12 \n" +
	"\x03app\x18\x01 \x01(\v2\x0e.developer.AppR\x03app\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x126\n" +
	"\vsigning_key\x18\x03 \x01(\v2\x15.developer.SigningKeyR\n" +
	"signingKey\"&\n" +
	"\rGetAppRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"H\n" +
	"\x0eGetAppResponse\x12 \n" +
	"\x03app\x18\x01 \x01(\v2\x0e.developer.AppR\x03app\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\",\n" +
	"\x13GetPublicAppRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"N\n" +
	"\x14GetPublicAppResponse\x12 \n" +
	"\x03app\x18\x01 \x01(\v2\x0e.developer.AppR\x03app\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"4\n" +
	"\x0fListAppsRequest\x12!\n" +
	"\fdeveloper_id\x18\x01 \x01(\tR\vdeveloperId\"6\n" +
	"\x10ListAppsResponse\x12\"\n" +
	"\x04apps\x18\x01 \x03(\v2\x0e.developer.AppR\x04apps\"\x9b\x02\n" +
	"\x10UpdateAppRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdeveloper_id\x18\x02 \x01(\tR\vdeveloperId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1e\n" +
	"\blogo_url\x18\x04 \x01(\tH\x01R\alogoUrl\x88\x01\x01\x12#\n" +
	"\rredirect_urls\x18\x05 \x03(\tR\fredirectUrls\x12A\n" +
	"\x1arequire_email_verification\x18\x06 \x01(\bH\x02R\x18requireEmailVerification\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_logo_urlB\x1d\n" +
	"\x1b_require_email_verification\"5\n" +
	"\x11UpdateAppResponse\x12 \n" +
	"\x03app\x18\x01 \x01(\v2\x0e.developer.AppR\x03app\"E\n" +
	"\x10DeleteAppRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdeveloper_id\x18\x02 \x01(\tR\vdeveloperId\"-\n" +
	"\x11DeleteAppResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb2\x02\n" +
	"\n" +
	"SigningKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x10\n" +
	"\x03kid\x18\x03 \x01(\tR\x03kid\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"rotated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\trotatedAt\"O\n" +
	"\x13RotateApiKeyRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12!\n" +
	"\fdeveloper_id\x18\x02 \x01(\tR\vdeveloperId\"6\n" +
	"\x14RotateApiKeyResponse\x12\x1e\n" +
	"\vnew_api_key\x18\x01 \x01(\tR\tnewApiKey\"E\n" +
	"\x13VerifyApiKeyRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\",\n" +
	"\x14VerifyApiKeyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"\x82\x01\n" +
	"\x18RotateSigningKeysRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12!\n" +
	"\fdeveloper_id\x18\x02 \x01(\tR\vdeveloperId\x12,\n" +
	"\x12grace_period_hours\x18\x03 \x01(\x05R\x10gracePeriodHours\"{\n" +
	"\x19RotateSigningKeysResponse\x12.\n" +
	"\anew_key\x18\x01 \x01(\v2\x15.developer.SigningKeyR\x06newKey\x12.\n" +
	"\aold_key\x18\x02 \x01(\v2\x15.developer.SigningKeyR\x06oldKey\"{\n" +
	"\x16ListSigningKeysRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12!\n" +
	"\fdeveloper_id\x18\x02 \x01(\tR\vdeveloperId\x12'\n" +
	"\x0finclude_expired\x18\x03 \x01(\bR\x0eincludeExpired\"D\n" +
	"\x17ListSigningKeysResponse\x12)\n" +
	"\x04keys\x18\x01 \x03(\v2\x15.developer.SigningKeyR\x04keys\"3\n" +
	"\x1aGetActiveSigningKeyRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"}\n" +
	"\x1bGetActiveSigningKeyResponse\x12'\n" +
	"\x03key\x18\x01 \x01(\v2\x15.developer.SigningKeyR\x03key\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\tR\n" +
	"privateKey\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"\xdc\x01\n" +
	"\rOAuthProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x16\n" +
	"\x06scopes\x18\x05 \x03(\tR\x06scopes\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc9\x01\n" +
	"\x17AddOAuthProviderRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12!\n" +
	"\fdeveloper_id\x18\x02 \x01(\tR\vdeveloperId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x05 \x01(\tR\fclientSecret\x12\x16\n" +
	"\x06scopes\x18\x06 \x03(\tR\x06scopes\"P\n" +
	"\x18AddOAuthProviderResponse\x124\n" +
	"\bprovider\x18\x01 \x01(\v2\x18.developer.OAuthProviderR\bprovider\"L\n" +
	"\x17GetOAuthProviderRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\x8b\x01\n" +
	"\x18GetOAuthProviderResponse\x124\n" +
	"\bprovider\x18\x01 \x01(\v2\x18.developer.OAuthProviderR\bprovider\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"U\n" +
	"\x19ListOAuthProvidersRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12!\n" +
	"\fdeveloper_id\x18\x02 \x01(\tR\vdeveloperId\"T\n" +
	"\x1aListOAuthProvidersResponse\x126\n" +
	"\tproviders\x18\x01 \x03(\v2\x18.developer.OAuthProviderR\tproviders\"\xa1\x02\n" +
	"\x1aUpdateOAuthProviderRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12!\n" +
	"\fdeveloper_id\x18\x02 \x01(\tR\vdeveloperId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12 \n" +
	"\tclient_id\x18\x04 \x01(\tH\x00R\bclientId\x88\x01\x01\x12(\n" +
	"\rclient_secret\x18\x05 \x01(\tH\x01R\fclientSecret\x88\x01\x01\x12\x16\n" +
	"\x06scopes\x18\x06 \x03(\tR\x06scopes\x12\x1d\n" +
	"\aenabled\x18\a \x01(\bH\x02R\aenabled\x88\x01\x01B\f\n" +
	"\n" +
	"_client_idB\x10\n" +
	"\x0e_client_secretB\n" +
	"\n" +
	"\b_enabled\"S\n" +
	"\x1bUpdateOAuthProviderResponse\x124\n" +
	"\bprovider\x18\x01 \x01(\v2\x18.developer.OAuthProviderR\bprovider\"r\n" +
	"\x1aDeleteOAuthProviderRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12!\n" +
	"\fdeveloper_id\x18\x02 \x01(\tR\vdeveloperId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\"7\n" +
	"\x1bDeleteOAuthProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc9\r\n" +
	"\x10DeveloperService\x12C\n" +
	"\bRegister\x12\x1a.developer.RegisterRequest\x1a\x1b.developer.RegisterResponse\x12:\n" +
	"\x05Login\x12\x17.developer.LoginRequest\x1a\x18.developer.LoginResponse\x12=\n" +
	"\x06Logout\x12\x18.developer.LogoutRequest\x1a\x19.developer.LogoutResponse\x12I\n" +
	"\n" +
	"GetProfile\x12\x1c.developer.GetProfileRequest\x1a\x1d.developer.GetProfileResponse\x12R\n" +
	"\rUpdateProfile\x12\x1f.developer.UpdateProfileRequest\x1a .developer.UpdateProfileResponse\x12F\n" +
	"\tCreateApp\x12\x1b.developer.CreateAppRequest\x1a\x1c.developer.CreateAppResponse\x12=\n" +
	"\x06GetApp\x12\x18.developer.GetAppRequest\x1a\x19.developer.GetAppResponse\x12O\n" +
	"\fGetPublicApp\x12\x1e.developer.GetPublicAppRequest\x1a\x1f.developer.GetPublicAppResponse\x12C\n" +
	"\bListApps\x12\x1a.developer.ListAppsRequest\x1a\x1b.developer.ListAppsResponse\x12F\n" +
	"\tUpdateApp\x12\x1b.developer.UpdateAppRequest\x1a\x1c.developer.UpdateAppResponse\x12F\n" +
	"\tDeleteApp\x12\x1b.developer.DeleteAppRequest\x1a\x1c.developer.DeleteAppResponse\x12O\n" +
	"\fRotateApiKey\x12\x1e.developer.RotateApiKeyRequest\x1a\x1f.developer.RotateApiKeyResponse\x12O\n" +
	"\fVerifyApiKey\x12\x1e.developer.VerifyApiKeyRequest\x1a\x1f.developer.VerifyApiKeyResponse\x12^\n" +
	"\x11RotateSigningKeys\x12#.developer.RotateSigningKeysRequest\x1a$.developer.RotateSigningKeysResponse\x12X\n" +
	"\x0fListSigningKeys\x12!.developer.ListSigningKeysRequest\x1a\".developer.ListSigningKeysResponse\x12d\n" +
	"\x13GetActiveSigningKey\x12%.developer.GetActiveSigningKeyRequest\x1a&.developer.GetActiveSigningKeyResponse\x12[\n" +
	"\x10AddOAuthProvider\x12\".developer.AddOAuthProviderRequest\x1a#.developer.AddOAuthProviderResponse\x12[\n" +
	"\x10GetOAuthProvider\x12\".developer.GetOAuthProviderRequest\x1a#.developer.GetOAuthProviderResponse\x12a\n" +
	"\x12ListOAuthProviders\x12$.developer.ListOAuthProvidersRequest\x1a%.developer.ListOAuthProvidersResponse\x12d\n" +
	"\x13UpdateOAuthProvider\x12%.developer.UpdateOAuthProviderRequest\x1a&.developer.UpdateOAuthProviderResponse\x12d\n" +
	"\x13DeleteOAuthProvider\x12%.developer.DeleteOAuthProviderRequest\x1a&.developer.DeleteOAuthProviderResponseB5Z3github.com/ayushdevan01/AuthService/proto/developerb\x06proto3"

var (
	file_proto_developer_developer_proto_rawDescOnce sync.Once
	file_proto_developer_developer_proto_rawDescData []byte
)

func file_proto_developer_developer_proto_rawDescGZIP() []byte {
	file_proto_developer_developer_proto_rawDescOnce.Do(func() {
		file_proto_developer_developer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_developer_developer_proto_rawDesc), len(file_proto_developer_developer_proto_rawDesc)))
	})
	return file_proto_developer_developer_proto_rawDescData
}

var file_proto_developer_developer_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_proto_developer_developer_proto_goTypes = []any{
	(*Developer)(nil),                   // 0: developer.Developer
	(*RegisterRequest)(nil),             // 1: developer.RegisterRequest
	(*RegisterResponse)(nil),            // 2: developer.RegisterResponse
	(*LoginRequest)(nil),                // 3: developer.LoginRequest
	(*LoginResponse)(nil),               // 4: developer.LoginResponse
	(*LogoutRequest)(nil),               // 5: developer.LogoutRequest
	(*LogoutResponse)(nil),              // 6: developer.LogoutResponse
	(*GetProfileRequest)(nil),           // 7: developer.GetProfileRequest
	(*GetProfileResponse)(nil),          // 8: developer.GetProfileResponse
	(*UpdateProfileRequest)(nil),        // 9: developer.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),       // 10: developer.UpdateProfileResponse
	(*App)(nil),                         // 11: developer.App
	(*CreateAppRequest)(nil),            // 12: developer.CreateAppRequest
	(*CreateAppResponse)(nil),           // 13: developer.CreateAppResponse
	(*GetAppRequest)(nil),               // 14: developer.GetAppRequest
	(*GetAppResponse)(nil),              // 15: developer.GetAppResponse
	(*GetPublicAppRequest)(nil),         // 16: developer.GetPublicAppRequest
	(*GetPublicAppResponse)(nil),        // 17: developer.GetPublicAppResponse
	(*ListAppsRequest)(nil),             // 18: developer.ListAppsRequest
	(*ListAppsResponse)(nil),            // 19: developer.ListAppsResponse
	(*UpdateAppRequest)(nil),            // 20: developer.UpdateAppRequest
	(*UpdateAppResponse)(nil),           // 21: developer.UpdateAppResponse
	(*DeleteAppRequest)(nil),            // 22: developer.DeleteAppRequest
	(*DeleteAppResponse)(nil),           // 23: developer.DeleteAppResponse
	(*SigningKey)(nil),                  // 24: developer.SigningKey
	(*RotateApiKeyRequest)(nil),         // 25: developer.RotateApiKeyRequest
	(*RotateApiKeyResponse)(nil),        // 26: developer.RotateApiKeyResponse
	(*VerifyApiKeyRequest)(nil),         // 27: developer.VerifyApiKeyRequest
	(*VerifyApiKeyResponse)(nil),        // 28: developer.VerifyApiKeyResponse
	(*RotateSigningKeysRequest)(nil),    // 29: developer.RotateSigningKeysRequest
	(*RotateSigningKeysResponse)(nil),   // 30: developer.RotateSigningKeysResponse
	(*ListSigningKeysRequest)(nil),      // 31: developer.ListSigningKeysRequest
	(*ListSigningKeysResponse)(nil),     // 32: developer.ListSigningKeysResponse
	(*GetActiveSigningKeyRequest)(nil),  // 33: developer.GetActiveSigningKeyRequest
	(*GetActiveSigningKeyResponse)(nil), // 34: developer.GetActiveSigningKeyResponse
	(*OAuthProvider)(nil),               // 35: developer.OAuthProvider
	(*AddOAuthProviderRequest)(nil),     // 36: developer.AddOAuthProviderRequest
	(*AddOAuthProviderResponse)(nil),    // 37: developer.AddOAuthProviderResponse
	(*GetOAuthProviderRequest)(nil),     // 38: developer.GetOAuthProviderRequest
	(*GetOAuthProviderResponse)(nil),    // 39: developer.GetOAuthProviderResponse
	(*ListOAuthProvidersRequest)(nil),   // 40: developer.ListOAuthProvidersRequest
	(*ListOAuthProvidersResponse)(nil),  // 41: developer.ListOAuthProvidersResponse
	(*UpdateOAuthProviderRequest)(nil),  // 42: developer.UpdateOAuthProviderRequest
	(*UpdateOAuthProviderResponse)(nil), // 43: developer.UpdateOAuthProviderResponse
	(*DeleteOAuthProviderRequest)(nil),  // 44: developer.DeleteOAuthProviderRequest
	(*DeleteOAuthProviderResponse)(nil), // 45: developer.DeleteOAuthProviderResponse
	(*timestamppb.Timestamp)(nil),       // 46: google.protobuf.Timestamp
}
var file_proto_developer_developer_proto_depIdxs = []int32{
	46, // 0: developer.Developer.created_at:type_name -> google.protobuf.Timestamp
	46, // 1: developer.Developer.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: developer.RegisterResponse.developer:type_name -> developer.Developer
	0,  // 3: developer.LoginResponse.developer:type_name -> developer.Developer
	0,  // 4: developer.GetProfileResponse.developer:type_name -> developer.Developer
	0,  // 5: developer.UpdateProfileResponse.developer:type_name -> developer.Developer
	46, // 6: developer.App.created_at:type_name -> google.protobuf.Timestamp
	46, // 7: developer.App.updated_at:type_name -> google.protobuf.Timestamp
	11, // 8: developer.CreateAppResponse.app:type_name -> developer.App
	24, // 9: developer.CreateAppResponse.signing_key:type_name -> developer.SigningKey
	11, // 10: developer.GetAppResponse.app:type_name -> developer.App
	11, // 11: developer.GetPublicAppResponse.app:type_name -> developer.App
	11, // 12: developer.ListAppsResponse.apps:type_name -> developer.App
	11, // 13: developer.UpdateAppResponse.app:type_name -> developer.App
	46, // 14: developer.SigningKey.created_at:type_name -> google.protobuf.Timestamp
	46, // 15: developer.SigningKey.expires_at:type_name -> google.protobuf.Timestamp
	46, // 16: developer.SigningKey.rotated_at:type_name -> google.protobuf.Timestamp
	24, // 17: developer.RotateSigningKeysResponse.new_key:type_name -> developer.SigningKey
	24, // 18: developer.RotateSigningKeysResponse.old_key:type_name -> developer.SigningKey
	24, // 19: developer.ListSigningKeysResponse.keys:type_name -> developer.SigningKey
	24, // 20: developer.GetActiveSigningKeyResponse.key:type_name -> developer.SigningKey
	46, // 21: developer.OAuthProvider.created_at:type_name -> google.protobuf.Timestamp
	35, // 22: developer.AddOAuthProviderResponse.provider:type_name -> developer.OAuthProvider
	35, // 23: developer.GetOAuthProviderResponse.provider:type_name -> developer.OAuthProvider
	35, // 24: developer.ListOAuthProvidersResponse.providers:type_name -> developer.OAuthProvider
	35, // 25: developer.UpdateOAuthProviderResponse.provider:type_name -> developer.OAuthProvider
	1,  // 26: developer.DeveloperService.Register:input_type -> developer.RegisterRequest
	3,  // 27: developer.DeveloperService.Login:input_type -> developer.LoginRequest
	5,  // 28: developer.DeveloperService.Logout:input_type -> developer.LogoutRequest
	7,  // 29: developer.DeveloperService.GetProfile:input_type -> developer.GetProfileRequest
	9,  // 30: developer.DeveloperService.UpdateProfile:input_type -> developer.UpdateProfileRequest
	12, // 31: developer.DeveloperService.CreateApp:input_type -> developer.CreateAppRequest
	14, // 32: developer.DeveloperService.GetApp:input_type -> developer.GetAppRequest
	16, // 33: developer.DeveloperService.GetPublicApp:input_type -> developer.GetPublicAppRequest
	18, // 34: developer.DeveloperService.ListApps:input_type -> developer.ListAppsRequest
	20, // 35: developer.DeveloperService.UpdateApp:input_type -> developer.UpdateAppRequest
	22, // 36: developer.DeveloperService.DeleteApp:input_type -> developer.DeleteAppRequest
	25, // 37: developer.DeveloperService.RotateApiKey:input_type -> developer.RotateApiKeyRequest
	27, // 38: developer.DeveloperService.VerifyApiKey:input_type -> developer.VerifyApiKeyRequest
	29, // 39: developer.DeveloperService.RotateSigningKeys:input_type -> developer.RotateSigningKeysRequest
	31, // 40: developer.DeveloperService.ListSigningKeys:input_type -> developer.ListSigningKeysRequest
	33, // 41: developer.DeveloperService.GetActiveSigningKey:input_type -> developer.GetActiveSigningKeyRequest
	36, // 42: developer.DeveloperService.AddOAuthProvider:input_type -> developer.AddOAuthProviderRequest
	38, // 43: developer.DeveloperService.GetOAuthProvider:input_type -> developer.GetOAuthProviderRequest
	40, // 44: developer.DeveloperService.ListOAuthProviders:input_type -> developer.ListOAuthProvidersRequest
	42, // 45: developer.DeveloperService.UpdateOAuthProvider:input_type -> developer.UpdateOAuthProviderRequest
	44, // 46: developer.DeveloperService.DeleteOAuthProvider:input_type -> developer.DeleteOAuthProviderRequest
	2,  // 47: developer.DeveloperService.Register:output_type -> developer.RegisterResponse
	4,  // 48: developer.DeveloperService.Login:output_type -> developer.LoginResponse
	6,  // 49: developer.DeveloperService.Logout:output_type -> developer.LogoutResponse
	8,  // 50: developer.DeveloperService.GetProfile:output_type -> developer.GetProfileResponse
	10, // 51: developer.DeveloperService.UpdateProfile:output_type -> developer.UpdateProfileResponse
	13, // 52: developer.DeveloperService.CreateApp:output_type -> developer.CreateAppResponse
	15, // 53: developer.DeveloperService.GetApp:output_type -> developer.GetAppResponse
	17, // 54: developer.DeveloperService.GetPublicApp:output_type -> developer.GetPublicAppResponse
	19, // 55: developer.DeveloperService.ListApps:output_type -> developer.ListAppsResponse
	21, // 56: developer.DeveloperService.UpdateApp:output_type -> developer.UpdateAppResponse
	23, // 57: developer.DeveloperService.DeleteApp:output_type -> developer.DeleteAppResponse
	26, // 58: developer.DeveloperService.RotateApiKey:output_type -> developer.RotateApiKeyResponse
	28, // 59: developer.DeveloperService.VerifyApiKey:output_type -> developer.VerifyApiKeyResponse
	30, // 60: developer.DeveloperService.RotateSigningKeys:output_type -> developer.RotateSigningKeysResponse
	32, // 61: developer.DeveloperService.ListSigningKeys:output_type -> developer.ListSigningKeysResponse
	34, // 62: developer.DeveloperService.GetActiveSigningKey:output_type -> developer.GetActiveSigningKeyResponse
	37, // 63: developer.DeveloperService.AddOAuthProvider:output_type -> developer.AddOAuthProviderResponse
	39, // 64: developer.DeveloperService.GetOAuthProvider:output_type -> developer.GetOAuthProviderResponse
	41, // 65: developer.DeveloperService.ListOAuthProviders:output_type -> developer.ListOAuthProvidersResponse
	43, // 66: developer.DeveloperService.UpdateOAuthProvider:output_type -> developer.UpdateOAuthProviderResponse
	45, // 67: developer.DeveloperService.DeleteOAuthProvider:output_type -> developer.DeleteOAuthProviderResponse
	47, // [47:68] is the sub-list for method output_type
	26, // [26:47] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_developer_developer_proto_init() }
func file_proto_developer_developer_proto_init() {
	if File_proto_developer_developer_proto != nil {
		return
	}
	file_proto_developer_developer_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_developer_developer_proto_msgTypes[20].OneofWrappers = []any{}
	file_proto_developer_developer_proto_msgTypes[42].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_developer_developer_proto_rawDesc), len(file_proto_developer_developer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_developer_developer_proto_goTypes,
		DependencyIndexes: file_proto_developer_developer_proto_depIdxs,
		MessageInfos:      file_proto_developer_developer_proto_msgTypes,
	}.Build()
	File_proto_developer_developer_proto = out.File
	file_proto_developer_developer_proto_goTypes = nil
	file_proto_developer_developer_proto_depIdxs = nil
}
